# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190809_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
