# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20190809_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='computedsentiment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
