# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_newsfeed_computedsentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='computedsentiment',
        ),
    ]
