# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_newsfeed_computedsentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='computedsentiments',
            field=models.CharField(default='', editable=False, max_length=256),
        ),
    ]
